# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(835, 628)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 791, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.tabnet = QtWidgets.QWidget()
        self.tabnet.setObjectName("tabnet")
        self.groupTrain = QtWidgets.QGroupBox(self.tabnet)
        self.groupTrain.setGeometry(QtCore.QRect(30, 20, 321, 231))
        self.groupTrain.setObjectName("groupTrain")
        self.label = QtWidgets.QLabel(self.groupTrain)
        self.label.setGeometry(QtCore.QRect(10, 40, 51, 16))
        self.label.setObjectName("label")
        self.txtT1OpenNet = QtWidgets.QLineEdit(self.groupTrain)
        self.txtT1OpenNet.setGeometry(QtCore.QRect(60, 40, 161, 20))
        self.txtT1OpenNet.setObjectName("txtT1OpenNet")
        self.btnT1OpenNet = QtWidgets.QPushButton(self.groupTrain)
        self.btnT1OpenNet.setGeometry(QtCore.QRect(230, 40, 61, 23))
        self.btnT1OpenNet.setObjectName("btnT1OpenNet")
        self.label_17 = QtWidgets.QLabel(self.groupTrain)
        self.label_17.setGeometry(QtCore.QRect(10, 80, 61, 20))
        self.label_17.setObjectName("label_17")
        self.txtT1BatchSize = QtWidgets.QLineEdit(self.groupTrain)
        self.txtT1BatchSize.setGeometry(QtCore.QRect(80, 80, 141, 20))
        self.txtT1BatchSize.setObjectName("txtT1BatchSize")
        self.label_18 = QtWidgets.QLabel(self.groupTrain)
        self.label_18.setGeometry(QtCore.QRect(40, 120, 31, 16))
        self.label_18.setObjectName("label_18")
        self.txtT1EPoch = QtWidgets.QLineEdit(self.groupTrain)
        self.txtT1EPoch.setGeometry(QtCore.QRect(80, 120, 141, 20))
        self.txtT1EPoch.setObjectName("txtT1EPoch")
        self.btnT1confirm1 = QtWidgets.QPushButton(self.groupTrain)
        self.btnT1confirm1.setGeometry(QtCore.QRect(220, 190, 75, 23))
        self.btnT1confirm1.setObjectName("btnT1confirm1")
        self.txtT1Path = QtWidgets.QLineEdit(self.groupTrain)
        self.txtT1Path.setGeometry(QtCore.QRect(60, 160, 161, 20))
        self.txtT1Path.setObjectName("txtT1Path")
        self.label_26 = QtWidgets.QLabel(self.groupTrain)
        self.label_26.setGeometry(QtCore.QRect(10, 160, 54, 12))
        self.label_26.setObjectName("label_26")
        self.groupBatNet = QtWidgets.QGroupBox(self.tabnet)
        self.groupBatNet.setGeometry(QtCore.QRect(370, 20, 381, 481))
        self.groupBatNet.setObjectName("groupBatNet")
        self.btnT1RemoveFile = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1RemoveFile.setGeometry(QtCore.QRect(290, 310, 75, 23))
        self.btnT1RemoveFile.setObjectName("btnT1RemoveFile")
        self.btnT1AddFile = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1AddFile.setGeometry(QtCore.QRect(290, 280, 75, 23))
        self.btnT1AddFile.setObjectName("btnT1AddFile")
        self.label_15 = QtWidgets.QLabel(self.groupBatNet)
        self.label_15.setGeometry(QtCore.QRect(30, 42, 91, 20))
        self.label_15.setObjectName("label_15")
        self.btnT1confirm3 = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1confirm3.setGeometry(QtCore.QRect(290, 430, 75, 23))
        self.btnT1confirm3.setObjectName("btnT1confirm3")
        self.btnT1RemoveAll = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1RemoveAll.setGeometry(QtCore.QRect(290, 340, 75, 23))
        self.btnT1RemoveAll.setObjectName("btnT1RemoveAll")
        self.btnT1ExportList = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1ExportList.setGeometry(QtCore.QRect(290, 370, 75, 23))
        self.btnT1ExportList.setObjectName("btnT1ExportList")
        self.btnT1ImportList = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1ImportList.setGeometry(QtCore.QRect(290, 400, 75, 23))
        self.btnT1ImportList.setObjectName("btnT1ImportList")
        self.lstT1NetList = QtWidgets.QListWidget(self.groupBatNet)
        self.lstT1NetList.setGeometry(QtCore.QRect(30, 70, 251, 381))
        self.lstT1NetList.setObjectName("lstT1NetList")
        self.groupImportNet = QtWidgets.QGroupBox(self.tabnet)
        self.groupImportNet.setGeometry(QtCore.QRect(30, 260, 321, 241))
        self.groupImportNet.setObjectName("groupImportNet")
        self.label_2 = QtWidgets.QLabel(self.groupImportNet)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 54, 12))
        self.label_2.setObjectName("label_2")
        self.btnT1ImportNet = QtWidgets.QPushButton(self.groupImportNet)
        self.btnT1ImportNet.setGeometry(QtCore.QRect(240, 40, 61, 23))
        self.btnT1ImportNet.setObjectName("btnT1ImportNet")
        self.txtT1ImportNet = QtWidgets.QLineEdit(self.groupImportNet)
        self.txtT1ImportNet.setGeometry(QtCore.QRect(70, 40, 161, 20))
        self.txtT1ImportNet.setObjectName("txtT1ImportNet")
        self.btnT1confirm2 = QtWidgets.QPushButton(self.groupImportNet)
        self.btnT1confirm2.setGeometry(QtCore.QRect(220, 180, 75, 23))
        self.btnT1confirm2.setObjectName("btnT1confirm2")
        self.tabWidget.addTab(self.tabnet, "")
        self.tabconfig = QtWidgets.QWidget()
        self.tabconfig.setObjectName("tabconfig")
        self.groupNewConfig = QtWidgets.QGroupBox(self.tabconfig)
        self.groupNewConfig.setGeometry(QtCore.QRect(30, 20, 321, 481))
        self.groupNewConfig.setObjectName("groupNewConfig")
        self.groupBox = QtWidgets.QGroupBox(self.groupNewConfig)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 281, 121))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label_3.setObjectName("label_3")
        self.cmbT2DO = QtWidgets.QComboBox(self.groupBox)
        self.cmbT2DO.setEnabled(True)
        self.cmbT2DO.setGeometry(QtCore.QRect(138, 20, 131, 22))
        self.cmbT2DO.setEditable(True)
        self.cmbT2DO.setObjectName("cmbT2DO")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(50, 50, 71, 16))
        self.label_4.setObjectName("label_4")
        self.txtT2CoreVMax = QtWidgets.QLineEdit(self.groupBox)
        self.txtT2CoreVMax.setGeometry(QtCore.QRect(140, 50, 131, 20))
        self.txtT2CoreVMax.setObjectName("txtT2CoreVMax")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(50, 80, 71, 20))
        self.label_5.setObjectName("label_5")
        self.txtT2CoreHMax = QtWidgets.QLineEdit(self.groupBox)
        self.txtT2CoreHMax.setGeometry(QtCore.QRect(140, 80, 131, 20))
        self.txtT2CoreHMax.setObjectName("txtT2CoreHMax")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupNewConfig)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 150, 281, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(70, 20, 41, 16))
        self.label_6.setObjectName("label_6")
        self.txtT2IOBits = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtT2IOBits.setGeometry(QtCore.QRect(140, 20, 131, 20))
        self.txtT2IOBits.setObjectName("txtT2IOBits")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(40, 50, 71, 16))
        self.label_7.setObjectName("label_7")
        self.txtT2ArrayCol = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtT2ArrayCol.setGeometry(QtCore.QRect(140, 50, 131, 20))
        self.txtT2ArrayCol.setObjectName("txtT2ArrayCol")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(40, 80, 71, 16))
        self.label_8.setObjectName("label_8")
        self.txtT2ArrayRow = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtT2ArrayRow.setGeometry(QtCore.QRect(140, 80, 131, 20))
        self.txtT2ArrayRow.setInputMask("")
        self.txtT2ArrayRow.setObjectName("txtT2ArrayRow")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupNewConfig)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 280, 281, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.label_9.setObjectName("label_9")
        self.cmbT2CellType = QtWidgets.QComboBox(self.groupBox_3)
        self.cmbT2CellType.setGeometry(QtCore.QRect(70, 20, 111, 22))
        self.cmbT2CellType.setEditable(True)
        self.cmbT2CellType.setCurrentText("")
        self.cmbT2CellType.setObjectName("cmbT2CellType")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.label_10.setObjectName("label_10")
        self.txtT2WeightBits = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtT2WeightBits.setGeometry(QtCore.QRect(70, 50, 51, 20))
        self.txtT2WeightBits.setObjectName("txtT2WeightBits")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 80, 51, 16))
        self.label_11.setObjectName("label_11")
        self.txtT2CellBits = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtT2CellBits.setGeometry(QtCore.QRect(70, 80, 51, 20))
        self.txtT2CellBits.setObjectName("txtT2CellBits")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(190, 20, 31, 16))
        self.label_12.setObjectName("label_12")
        self.txtT2RMin = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtT2RMin.setGeometry(QtCore.QRect(220, 20, 41, 20))
        self.txtT2RMin.setObjectName("txtT2RMin")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(160, 50, 31, 20))
        self.label_13.setObjectName("label_13")
        self.txtT2RMax = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtT2RMax.setGeometry(QtCore.QRect(200, 50, 61, 20))
        self.txtT2RMax.setObjectName("txtT2RMax")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(130, 80, 71, 20))
        self.label_14.setObjectName("label_14")
        self.txtT2Voltage = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtT2Voltage.setGeometry(QtCore.QRect(200, 80, 61, 20))
        self.txtT2Voltage.setObjectName("txtT2Voltage")
        self.btnT2Default = QtWidgets.QPushButton(self.groupNewConfig)
        self.btnT2Default.setGeometry(QtCore.QRect(30, 430, 61, 23))
        self.btnT2Default.setObjectName("btnT2Default")
        self.btnT2Read = QtWidgets.QPushButton(self.groupNewConfig)
        self.btnT2Read.setGeometry(QtCore.QRect(100, 430, 61, 23))
        self.btnT2Read.setObjectName("btnT2Read")
        self.btnT2Save = QtWidgets.QPushButton(self.groupNewConfig)
        self.btnT2Save.setGeometry(QtCore.QRect(170, 430, 61, 23))
        self.btnT2Save.setObjectName("btnT2Save")
        self.btnT2Confirm1 = QtWidgets.QPushButton(self.groupNewConfig)
        self.btnT2Confirm1.setGeometry(QtCore.QRect(240, 430, 61, 23))
        self.btnT2Confirm1.setObjectName("btnT2Confirm1")
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.btnT2Default.raise_()
        self.btnT2Read.raise_()
        self.btnT2Save.raise_()
        self.btnT2Confirm1.raise_()
        self.groupBatConfig = QtWidgets.QGroupBox(self.tabconfig)
        self.groupBatConfig.setGeometry(QtCore.QRect(370, 20, 381, 481))
        self.groupBatConfig.setObjectName("groupBatConfig")
        self.btnT2ExportList = QtWidgets.QPushButton(self.groupBatConfig)
        self.btnT2ExportList.setGeometry(QtCore.QRect(290, 370, 75, 23))
        self.btnT2ExportList.setObjectName("btnT2ExportList")
        self.btnT2RemoveAll = QtWidgets.QPushButton(self.groupBatConfig)
        self.btnT2RemoveAll.setGeometry(QtCore.QRect(290, 340, 75, 23))
        self.btnT2RemoveAll.setObjectName("btnT2RemoveAll")
        self.btnT2Confirm2 = QtWidgets.QPushButton(self.groupBatConfig)
        self.btnT2Confirm2.setGeometry(QtCore.QRect(290, 430, 75, 23))
        self.btnT2Confirm2.setObjectName("btnT2Confirm2")
        self.btnT2RemoveFile = QtWidgets.QPushButton(self.groupBatConfig)
        self.btnT2RemoveFile.setGeometry(QtCore.QRect(290, 310, 75, 23))
        self.btnT2RemoveFile.setObjectName("btnT2RemoveFile")
        self.label_16 = QtWidgets.QLabel(self.groupBatConfig)
        self.label_16.setGeometry(QtCore.QRect(30, 42, 81, 20))
        self.label_16.setObjectName("label_16")
        self.btnT2AddFile = QtWidgets.QPushButton(self.groupBatConfig)
        self.btnT2AddFile.setGeometry(QtCore.QRect(290, 280, 75, 23))
        self.btnT2AddFile.setObjectName("btnT2AddFile")
        self.btnT2ImportList = QtWidgets.QPushButton(self.groupBatConfig)
        self.btnT2ImportList.setGeometry(QtCore.QRect(290, 400, 75, 23))
        self.btnT2ImportList.setObjectName("btnT2ImportList")
        self.lstT2ConfigList = QtWidgets.QListWidget(self.groupBatConfig)
        self.lstT2ConfigList.setGeometry(QtCore.QRect(30, 70, 251, 381))
        self.lstT2ConfigList.setObjectName("lstT2ConfigList")
        self.tabWidget.addTab(self.tabconfig, "")
        self.tabcase = QtWidgets.QWidget()
        self.tabcase.setObjectName("tabcase")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tabcase)
        self.groupBox_6.setGeometry(QtCore.QRect(30, 20, 721, 481))
        self.groupBox_6.setObjectName("groupBox_6")
        self.btnT3RemoveAllNet = QtWidgets.QPushButton(self.groupBox_6)
        self.btnT3RemoveAllNet.setGeometry(QtCore.QRect(280, 250, 75, 23))
        self.btnT3RemoveAllNet.setObjectName("btnT3RemoveAllNet")
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        self.label_19.setGeometry(QtCore.QRect(40, 30, 101, 16))
        self.label_19.setObjectName("label_19")
        self.btnT3RemoveNet = QtWidgets.QPushButton(self.groupBox_6)
        self.btnT3RemoveNet.setGeometry(QtCore.QRect(280, 220, 75, 23))
        self.btnT3RemoveNet.setObjectName("btnT3RemoveNet")
        self.btnT3AddNet = QtWidgets.QPushButton(self.groupBox_6)
        self.btnT3AddNet.setGeometry(QtCore.QRect(280, 190, 75, 23))
        self.btnT3AddNet.setObjectName("btnT3AddNet")
        self.lstT3NetList = QtWidgets.QListWidget(self.groupBox_6)
        self.lstT3NetList.setGeometry(QtCore.QRect(40, 50, 231, 231))
        self.lstT3NetList.setObjectName("lstT3NetList")
        self.btnT3RemoveConfig = QtWidgets.QPushButton(self.groupBox_6)
        self.btnT3RemoveConfig.setGeometry(QtCore.QRect(630, 220, 75, 23))
        self.btnT3RemoveConfig.setObjectName("btnT3RemoveConfig")
        self.lstT3ConfigList = QtWidgets.QListWidget(self.groupBox_6)
        self.lstT3ConfigList.setGeometry(QtCore.QRect(380, 50, 231, 231))
        self.lstT3ConfigList.setObjectName("lstT3ConfigList")
        self.btnT3AddConfig = QtWidgets.QPushButton(self.groupBox_6)
        self.btnT3AddConfig.setGeometry(QtCore.QRect(630, 190, 75, 23))
        self.btnT3AddConfig.setObjectName("btnT3AddConfig")
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(380, 30, 81, 16))
        self.label_20.setObjectName("label_20")
        self.btnT3RemoveAllConfig = QtWidgets.QPushButton(self.groupBox_6)
        self.btnT3RemoveAllConfig.setGeometry(QtCore.QRect(630, 250, 75, 23))
        self.btnT3RemoveAllConfig.setObjectName("btnT3RemoveAllConfig")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_4.setGeometry(QtCore.QRect(40, 290, 411, 171))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(40, 140, 54, 12))
        self.label_27.setObjectName("label_27")
        self.txtT3BatchSize = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtT3BatchSize.setGeometry(QtCore.QRect(110, 60, 141, 20))
        self.txtT3BatchSize.setObjectName("txtT3BatchSize")
        self.txtT3OpenNet = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtT3OpenNet.setGeometry(QtCore.QRect(90, 20, 161, 20))
        self.txtT3OpenNet.setObjectName("txtT3OpenNet")
        self.txtT3EPoch = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtT3EPoch.setGeometry(QtCore.QRect(110, 100, 141, 20))
        self.txtT3EPoch.setObjectName("txtT3EPoch")
        self.txtT3Path = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtT3Path.setGeometry(QtCore.QRect(90, 140, 161, 20))
        self.txtT3Path.setObjectName("txtT3Path")
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(70, 100, 31, 16))
        self.label_25.setObjectName("label_25")
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(40, 60, 61, 20))
        self.label_24.setObjectName("label_24")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(30, 20, 51, 16))
        self.label_23.setObjectName("label_23")
        self.pushButton_29 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_29.setGeometry(QtCore.QRect(260, 20, 61, 23))
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_30.setGeometry(QtCore.QRect(260, 140, 61, 23))
        self.pushButton_30.setObjectName("pushButton_30")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_5.setGeometry(QtCore.QRect(480, 290, 121, 171))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_39 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_39.setGeometry(QtCore.QRect(20, 90, 75, 23))
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_40.setGeometry(QtCore.QRect(20, 120, 75, 23))
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_37 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_37.setGeometry(QtCore.QRect(20, 30, 75, 23))
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_38.setGeometry(QtCore.QRect(20, 60, 75, 23))
        self.pushButton_38.setObjectName("pushButton_38")
        self.tabWidget.addTab(self.tabcase, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.groupBox_8 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_8.setGeometry(QtCore.QRect(30, 270, 321, 231))
        self.groupBox_8.setObjectName("groupBox_8")
        self.listView_8 = QtWidgets.QListView(self.groupBox_8)
        self.listView_8.setGeometry(QtCore.QRect(30, 30, 261, 181))
        self.listView_8.setObjectName("listView_8")
        self.groupBox_7 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_7.setGeometry(QtCore.QRect(30, 20, 321, 231))
        self.groupBox_7.setObjectName("groupBox_7")
        self.listView_7 = QtWidgets.QListView(self.groupBox_7)
        self.listView_7.setGeometry(QtCore.QRect(30, 30, 261, 181))
        self.listView_7.setObjectName("listView_7")
        self.groupBox_9 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_9.setGeometry(QtCore.QRect(370, 20, 381, 481))
        self.groupBox_9.setObjectName("groupBox_9")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_12.setGeometry(QtCore.QRect(30, 30, 321, 201))
        self.groupBox_12.setObjectName("groupBox_12")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox.setGeometry(QtCore.QRect(30, 30, 71, 16))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_2.setGeometry(QtCore.QRect(30, 60, 71, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 90, 71, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_4.setGeometry(QtCore.QRect(30, 120, 71, 16))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_5.setGeometry(QtCore.QRect(30, 150, 71, 16))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_6.setGeometry(QtCore.QRect(150, 120, 71, 16))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_7.setGeometry(QtCore.QRect(150, 150, 71, 16))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_8.setGeometry(QtCore.QRect(150, 30, 71, 16))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_9.setGeometry(QtCore.QRect(150, 90, 71, 16))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_10.setGeometry(QtCore.QRect(150, 60, 71, 16))
        self.checkBox_10.setObjectName("checkBox_10")
        self.pushButton_35 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_35.setGeometry(QtCore.QRect(230, 160, 75, 23))
        self.pushButton_35.setObjectName("pushButton_35")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_13.setGeometry(QtCore.QRect(30, 250, 321, 201))
        self.groupBox_13.setObjectName("groupBox_13")
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_11.setGeometry(QtCore.QRect(150, 30, 71, 16))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_12.setGeometry(QtCore.QRect(150, 120, 71, 16))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_13.setGeometry(QtCore.QRect(30, 150, 71, 16))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_14.setGeometry(QtCore.QRect(150, 90, 71, 16))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_15.setGeometry(QtCore.QRect(30, 30, 71, 16))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_16.setGeometry(QtCore.QRect(30, 90, 71, 16))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_17.setGeometry(QtCore.QRect(30, 60, 71, 16))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_18.setGeometry(QtCore.QRect(150, 150, 71, 16))
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_19.setGeometry(QtCore.QRect(30, 120, 71, 16))
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_20.setGeometry(QtCore.QRect(150, 60, 71, 16))
        self.checkBox_20.setObjectName("checkBox_20")
        self.pushButton_41 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_41.setGeometry(QtCore.QRect(230, 160, 75, 23))
        self.pushButton_41.setObjectName("pushButton_41")
        self.tabWidget.addTab(self.widget, "")
        self.tabresult = QtWidgets.QWidget()
        self.tabresult.setObjectName("tabresult")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tabresult)
        self.groupBox_10.setGeometry(QtCore.QRect(30, 20, 321, 481))
        self.groupBox_10.setObjectName("groupBox_10")
        self.listView_9 = QtWidgets.QListView(self.groupBox_10)
        self.listView_9.setGeometry(QtCore.QRect(30, 40, 251, 381))
        self.listView_9.setObjectName("listView_9")
        self.pushButton_31 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_31.setGeometry(QtCore.QRect(210, 430, 75, 23))
        self.pushButton_31.setObjectName("pushButton_31")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tabresult)
        self.groupBox_11.setGeometry(QtCore.QRect(370, 20, 381, 481))
        self.groupBox_11.setObjectName("groupBox_11")
        self.listView_10 = QtWidgets.QListView(self.groupBox_11)
        self.listView_10.setGeometry(QtCore.QRect(40, 40, 311, 381))
        self.listView_10.setObjectName("listView_10")
        self.pushButton_34 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_34.setGeometry(QtCore.QRect(280, 430, 75, 23))
        self.pushButton_34.setObjectName("pushButton_34")
        self.tabWidget.addTab(self.tabresult, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 835, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.cmbT2DO.setCurrentIndex(-1)
        self.cmbT2CellType.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupTrain.setTitle(_translate("MainWindow", "训练网络"))
        self.label.setText(_translate("MainWindow", "选择网络"))
        self.btnT1OpenNet.setText(_translate("MainWindow", "打开文件"))
        self.label_17.setText(_translate("MainWindow", "Batch Size"))
        self.label_18.setText(_translate("MainWindow", "EPoch"))
        self.btnT1confirm1.setText(_translate("MainWindow", "确定"))
        self.label_26.setText(_translate("MainWindow", "生成路径"))
        self.groupBatNet.setTitle(_translate("MainWindow", "批量网络处理"))
        self.btnT1RemoveFile.setText(_translate("MainWindow", "删除文件"))
        self.btnT1AddFile.setText(_translate("MainWindow", "添加文件"))
        self.label_15.setText(_translate("MainWindow", "网络文件列表"))
        self.btnT1confirm3.setText(_translate("MainWindow", "确定"))
        self.btnT1RemoveAll.setText(_translate("MainWindow", "清空列表"))
        self.btnT1ExportList.setText(_translate("MainWindow", "导出列表"))
        self.btnT1ImportList.setText(_translate("MainWindow", "读取列表"))
        self.groupImportNet.setTitle(_translate("MainWindow", "导入现有网络数据"))
        self.label_2.setText(_translate("MainWindow", "导入网络"))
        self.btnT1ImportNet.setText(_translate("MainWindow", "打开文件"))
        self.btnT1confirm2.setText(_translate("MainWindow", "确定"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabnet), _translate("MainWindow", "Net"))
        self.groupNewConfig.setTitle(_translate("MainWindow", "设置新的配置文件"))
        self.groupBox.setTitle(_translate("MainWindow", "System Parameters"))
        self.label_3.setText(_translate("MainWindow", "DesignOptimization"))
        self.cmbT2DO.setCurrentText(_translate("MainWindow", "None"))
        self.label_4.setText(_translate("MainWindow", "numCoreVMax"))
        self.txtT2CoreVMax.setText(_translate("MainWindow", "20"))
        self.label_5.setText(_translate("MainWindow", "numCoreHMax"))
        self.txtT2CoreHMax.setText(_translate("MainWindow", "20"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Core Parameters"))
        self.label_6.setText(_translate("MainWindow", "IOBits"))
        self.txtT2IOBits.setText(_translate("MainWindow", "8"))
        self.label_7.setText(_translate("MainWindow", "numArrayCol"))
        self.txtT2ArrayCol.setText(_translate("MainWindow", "256"))
        self.label_8.setText(_translate("MainWindow", "numArrayRow "))
        self.txtT2ArrayRow.setText(_translate("MainWindow", "256"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Cell Parameters"))
        self.label_9.setText(_translate("MainWindow", "CellType"))
        self.label_10.setText(_translate("MainWindow", "WeightBits"))
        self.txtT2WeightBits.setText(_translate("MainWindow", "8"))
        self.label_11.setText(_translate("MainWindow", "CellBits"))
        self.txtT2CellBits.setText(_translate("MainWindow", "4"))
        self.label_12.setText(_translate("MainWindow", "Rmin"))
        self.txtT2RMin.setText(_translate("MainWindow", "25e3"))
        self.label_13.setText(_translate("MainWindow", "Rmax"))
        self.txtT2RMax.setText(_translate("MainWindow", "265e3"))
        self.label_14.setText(_translate("MainWindow", "ReadVoltage"))
        self.txtT2Voltage.setText(_translate("MainWindow", "0.15"))
        self.btnT2Default.setText(_translate("MainWindow", "恢复默认"))
        self.btnT2Read.setText(_translate("MainWindow", "读取配置"))
        self.btnT2Save.setText(_translate("MainWindow", "保存配置"))
        self.btnT2Confirm1.setText(_translate("MainWindow", "确定"))
        self.groupBatConfig.setTitle(_translate("MainWindow", "批量配置文件设置"))
        self.btnT2ExportList.setText(_translate("MainWindow", "导出列表"))
        self.btnT2RemoveAll.setText(_translate("MainWindow", "清空列表"))
        self.btnT2Confirm2.setText(_translate("MainWindow", "确定"))
        self.btnT2RemoveFile.setText(_translate("MainWindow", "删除文件"))
        self.label_16.setText(_translate("MainWindow", "配置文件列表"))
        self.btnT2AddFile.setText(_translate("MainWindow", "添加文件"))
        self.btnT2ImportList.setText(_translate("MainWindow", "读取列表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabconfig), _translate("MainWindow", "Config"))
        self.groupBox_6.setTitle(_translate("MainWindow", "用例设定"))
        self.btnT3RemoveAllNet.setText(_translate("MainWindow", "清空列表"))
        self.label_19.setText(_translate("MainWindow", "网络数据文件列表"))
        self.btnT3RemoveNet.setText(_translate("MainWindow", "删除"))
        self.btnT3AddNet.setText(_translate("MainWindow", "添加"))
        self.btnT3RemoveConfig.setText(_translate("MainWindow", "删除"))
        self.btnT3AddConfig.setText(_translate("MainWindow", "添加"))
        self.label_20.setText(_translate("MainWindow", "配置文件列表"))
        self.btnT3RemoveAllConfig.setText(_translate("MainWindow", "清空列表"))
        self.groupBox_4.setTitle(_translate("MainWindow", "训练网络"))
        self.label_27.setText(_translate("MainWindow", "生成路径"))
        self.label_25.setText(_translate("MainWindow", "EPoch"))
        self.label_24.setText(_translate("MainWindow", "Batch Size"))
        self.label_23.setText(_translate("MainWindow", "选择网络"))
        self.pushButton_29.setText(_translate("MainWindow", "打开文件"))
        self.pushButton_30.setText(_translate("MainWindow", "打开文件"))
        self.groupBox_5.setTitle(_translate("MainWindow", "用例设置"))
        self.pushButton_39.setText(_translate("MainWindow", "清空设置"))
        self.pushButton_40.setText(_translate("MainWindow", "确定"))
        self.pushButton_37.setText(_translate("MainWindow", "读取用例"))
        self.pushButton_38.setText(_translate("MainWindow", "保存用例"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabcase), _translate("MainWindow", "TestCase"))
        self.groupBox_8.setTitle(_translate("MainWindow", "配置文件信息"))
        self.groupBox_7.setTitle(_translate("MainWindow", "网络信息"))
        self.groupBox_9.setTitle(_translate("MainWindow", "硬件模拟设置"))
        self.groupBox_12.setTitle(_translate("MainWindow", "结果分析选项"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_2.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_3.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_4.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_5.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_6.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_7.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_8.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_9.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_10.setText(_translate("MainWindow", "CheckBox"))
        self.pushButton_35.setText(_translate("MainWindow", "PushButton"))
        self.groupBox_13.setTitle(_translate("MainWindow", "结果显示设置"))
        self.checkBox_11.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_12.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_13.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_14.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_15.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_16.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_17.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_18.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_19.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_20.setText(_translate("MainWindow", "CheckBox"))
        self.pushButton_41.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "Hardware Simulation"))
        self.groupBox_10.setTitle(_translate("MainWindow", "结果显示"))
        self.pushButton_31.setText(_translate("MainWindow", "保存结果"))
        self.groupBox_11.setTitle(_translate("MainWindow", "分析显示"))
        self.pushButton_34.setText(_translate("MainWindow", "保存分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabresult), _translate("MainWindow", "Result"))

