# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(835, 616)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 791, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.tabnet = QtWidgets.QWidget()
        self.tabnet.setObjectName("tabnet")
        self.groupTrain = QtWidgets.QGroupBox(self.tabnet)
        self.groupTrain.setGeometry(QtCore.QRect(30, 20, 321, 271))
        self.groupTrain.setObjectName("groupTrain")
        self.label = QtWidgets.QLabel(self.groupTrain)
        self.label.setGeometry(QtCore.QRect(10, 40, 51, 16))
        self.label.setObjectName("label")
        self.txtT1OpenNet = QtWidgets.QLineEdit(self.groupTrain)
        self.txtT1OpenNet.setGeometry(QtCore.QRect(60, 40, 161, 20))
        self.txtT1OpenNet.setObjectName("txtT1OpenNet")
        self.btnT1OpenNet = QtWidgets.QPushButton(self.groupTrain)
        self.btnT1OpenNet.setGeometry(QtCore.QRect(230, 40, 61, 23))
        self.btnT1OpenNet.setObjectName("btnT1OpenNet")
        self.label_17 = QtWidgets.QLabel(self.groupTrain)
        self.label_17.setGeometry(QtCore.QRect(10, 80, 61, 20))
        self.label_17.setObjectName("label_17")
        self.txtT1BatchSize = QtWidgets.QLineEdit(self.groupTrain)
        self.txtT1BatchSize.setGeometry(QtCore.QRect(80, 80, 141, 20))
        self.txtT1BatchSize.setObjectName("txtT1BatchSize")
        self.label_18 = QtWidgets.QLabel(self.groupTrain)
        self.label_18.setGeometry(QtCore.QRect(40, 120, 31, 16))
        self.label_18.setObjectName("label_18")
        self.txtT1EPoch = QtWidgets.QLineEdit(self.groupTrain)
        self.txtT1EPoch.setGeometry(QtCore.QRect(80, 120, 141, 20))
        self.txtT1EPoch.setObjectName("txtT1EPoch")
        self.btnT1confirm1 = QtWidgets.QPushButton(self.groupTrain)
        self.btnT1confirm1.setGeometry(QtCore.QRect(220, 230, 75, 23))
        self.btnT1confirm1.setObjectName("btnT1confirm1")
        self.cmbT1NetType = QtWidgets.QComboBox(self.groupTrain)
        self.cmbT1NetType.setGeometry(QtCore.QRect(80, 200, 141, 22))
        self.cmbT1NetType.setEditable(True)
        self.cmbT1NetType.setObjectName("cmbT1NetType")
        self.btnT1PathSelection = QtWidgets.QPushButton(self.groupTrain)
        self.btnT1PathSelection.setGeometry(QtCore.QRect(230, 160, 61, 23))
        self.btnT1PathSelection.setObjectName("btnT1PathSelection")
        self.label_71 = QtWidgets.QLabel(self.groupTrain)
        self.label_71.setGeometry(QtCore.QRect(20, 200, 51, 20))
        self.label_71.setObjectName("label_71")
        self.txtT1OutputPath = QtWidgets.QLineEdit(self.groupTrain)
        self.txtT1OutputPath.setGeometry(QtCore.QRect(80, 160, 141, 20))
        self.txtT1OutputPath.setObjectName("txtT1OutputPath")
        self.label_72 = QtWidgets.QLabel(self.groupTrain)
        self.label_72.setGeometry(QtCore.QRect(20, 160, 51, 16))
        self.label_72.setObjectName("label_72")
        self.groupBatNet = QtWidgets.QGroupBox(self.tabnet)
        self.groupBatNet.setGeometry(QtCore.QRect(370, 20, 381, 481))
        self.groupBatNet.setObjectName("groupBatNet")
        self.btnT1RemoveFile = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1RemoveFile.setGeometry(QtCore.QRect(290, 100, 75, 23))
        self.btnT1RemoveFile.setObjectName("btnT1RemoveFile")
        self.btnT1AddFile = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1AddFile.setGeometry(QtCore.QRect(290, 70, 75, 23))
        self.btnT1AddFile.setObjectName("btnT1AddFile")
        self.label_15 = QtWidgets.QLabel(self.groupBatNet)
        self.label_15.setGeometry(QtCore.QRect(30, 42, 121, 20))
        self.label_15.setObjectName("label_15")
        self.btnT1confirm2 = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1confirm2.setGeometry(QtCore.QRect(290, 220, 75, 23))
        self.btnT1confirm2.setObjectName("btnT1confirm2")
        self.btnT1RemoveAll = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1RemoveAll.setGeometry(QtCore.QRect(290, 130, 75, 23))
        self.btnT1RemoveAll.setObjectName("btnT1RemoveAll")
        self.btnT1ExportList = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1ExportList.setGeometry(QtCore.QRect(290, 160, 75, 23))
        self.btnT1ExportList.setObjectName("btnT1ExportList")
        self.btnT1ImportList = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1ImportList.setGeometry(QtCore.QRect(290, 190, 75, 23))
        self.btnT1ImportList.setObjectName("btnT1ImportList")
        self.lstT1NetList = QtWidgets.QListWidget(self.groupBatNet)
        self.lstT1NetList.setGeometry(QtCore.QRect(30, 70, 251, 171))
        self.lstT1NetList.setObjectName("lstT1NetList")
        self.btnT1confirm3 = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1confirm3.setGeometry(QtCore.QRect(290, 440, 75, 23))
        self.btnT1confirm3.setObjectName("btnT1confirm3")
        self.label_21 = QtWidgets.QLabel(self.groupBatNet)
        self.label_21.setGeometry(QtCore.QRect(30, 262, 111, 20))
        self.label_21.setObjectName("label_21")
        self.lstT1ImageList = QtWidgets.QListWidget(self.groupBatNet)
        self.lstT1ImageList.setGeometry(QtCore.QRect(30, 290, 251, 171))
        self.lstT1ImageList.setObjectName("lstT1ImageList")
        self.btnT1AddFile_2 = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1AddFile_2.setGeometry(QtCore.QRect(290, 290, 75, 23))
        self.btnT1AddFile_2.setObjectName("btnT1AddFile_2")
        self.btnT1RemoveAll_2 = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1RemoveAll_2.setGeometry(QtCore.QRect(290, 350, 75, 23))
        self.btnT1RemoveAll_2.setObjectName("btnT1RemoveAll_2")
        self.btnT1ExportList_2 = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1ExportList_2.setGeometry(QtCore.QRect(290, 380, 75, 23))
        self.btnT1ExportList_2.setObjectName("btnT1ExportList_2")
        self.btnT1ImportList_2 = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1ImportList_2.setGeometry(QtCore.QRect(290, 410, 75, 23))
        self.btnT1ImportList_2.setObjectName("btnT1ImportList_2")
        self.btnT1RemoveFile_2 = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1RemoveFile_2.setGeometry(QtCore.QRect(290, 320, 75, 23))
        self.btnT1RemoveFile_2.setObjectName("btnT1RemoveFile_2")
        self.groupBox_31 = QtWidgets.QGroupBox(self.tabnet)
        self.groupBox_31.setGeometry(QtCore.QRect(30, 300, 321, 201))
        self.groupBox_31.setObjectName("groupBox_31")
        self.cmbT1NetType_2 = QtWidgets.QComboBox(self.groupBox_31)
        self.cmbT1NetType_2.setGeometry(QtCore.QRect(240, 20, 61, 22))
        self.cmbT1NetType_2.setEditable(True)
        self.cmbT1NetType_2.setObjectName("cmbT1NetType_2")
        self.label_73 = QtWidgets.QLabel(self.groupBox_31)
        self.label_73.setGeometry(QtCore.QRect(180, 20, 51, 20))
        self.label_73.setObjectName("label_73")
        self.lstT1TypeList = QtWidgets.QListWidget(self.groupBox_31)
        self.lstT1TypeList.setGeometry(QtCore.QRect(180, 50, 121, 111))
        self.lstT1TypeList.setObjectName("lstT1TypeList")
        self.btnT1RemoveType = QtWidgets.QPushButton(self.groupBox_31)
        self.btnT1RemoveType.setGeometry(QtCore.QRect(240, 160, 61, 23))
        self.btnT1RemoveType.setObjectName("btnT1RemoveType")
        self.btnT1AddType = QtWidgets.QPushButton(self.groupBox_31)
        self.btnT1AddType.setGeometry(QtCore.QRect(180, 160, 61, 23))
        self.btnT1AddType.setObjectName("btnT1AddType")
        self.btnT1RemoveSize = QtWidgets.QPushButton(self.groupBox_31)
        self.btnT1RemoveSize.setGeometry(QtCore.QRect(90, 160, 61, 23))
        self.btnT1RemoveSize.setObjectName("btnT1RemoveSize")
        self.label_22 = QtWidgets.QLabel(self.groupBox_31)
        self.label_22.setGeometry(QtCore.QRect(30, 20, 61, 20))
        self.label_22.setObjectName("label_22")
        self.lstT1SizeList = QtWidgets.QListWidget(self.groupBox_31)
        self.lstT1SizeList.setGeometry(QtCore.QRect(30, 50, 121, 111))
        self.lstT1SizeList.setObjectName("lstT1SizeList")
        self.txtT1BatchSize_3 = QtWidgets.QLineEdit(self.groupBox_31)
        self.txtT1BatchSize_3.setGeometry(QtCore.QRect(100, 20, 51, 20))
        self.txtT1BatchSize_3.setObjectName("txtT1BatchSize_3")
        self.btnT1AddSize = QtWidgets.QPushButton(self.groupBox_31)
        self.btnT1AddSize.setGeometry(QtCore.QRect(30, 160, 61, 23))
        self.btnT1AddSize.setObjectName("btnT1AddSize")
        self.tabWidget.addTab(self.tabnet, "")
        self.tabconfig = QtWidgets.QWidget()
        self.tabconfig.setObjectName("tabconfig")
        self.groupNewConfig = QtWidgets.QGroupBox(self.tabconfig)
        self.groupNewConfig.setGeometry(QtCore.QRect(30, 20, 321, 481))
        self.groupNewConfig.setObjectName("groupNewConfig")
        self.groupBox = QtWidgets.QGroupBox(self.groupNewConfig)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 281, 121))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label_3.setObjectName("label_3")
        self.cmbT2DO = QtWidgets.QComboBox(self.groupBox)
        self.cmbT2DO.setEnabled(True)
        self.cmbT2DO.setGeometry(QtCore.QRect(138, 20, 131, 22))
        self.cmbT2DO.setEditable(True)
        self.cmbT2DO.setCurrentText("")
        self.cmbT2DO.setObjectName("cmbT2DO")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(50, 50, 71, 16))
        self.label_4.setObjectName("label_4")
        self.txtT2CoreVMax = QtWidgets.QLineEdit(self.groupBox)
        self.txtT2CoreVMax.setGeometry(QtCore.QRect(140, 50, 131, 20))
        self.txtT2CoreVMax.setObjectName("txtT2CoreVMax")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(50, 80, 71, 20))
        self.label_5.setObjectName("label_5")
        self.txtT2CoreHMax = QtWidgets.QLineEdit(self.groupBox)
        self.txtT2CoreHMax.setGeometry(QtCore.QRect(140, 80, 131, 20))
        self.txtT2CoreHMax.setObjectName("txtT2CoreHMax")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupNewConfig)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 150, 281, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(70, 20, 41, 16))
        self.label_6.setObjectName("label_6")
        self.txtT2IOBits = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtT2IOBits.setGeometry(QtCore.QRect(140, 20, 131, 20))
        self.txtT2IOBits.setObjectName("txtT2IOBits")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(40, 50, 71, 16))
        self.label_7.setObjectName("label_7")
        self.txtT2ArrayCol = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtT2ArrayCol.setGeometry(QtCore.QRect(140, 50, 131, 20))
        self.txtT2ArrayCol.setObjectName("txtT2ArrayCol")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(40, 80, 71, 16))
        self.label_8.setObjectName("label_8")
        self.txtT2ArrayRow = QtWidgets.QLineEdit(self.groupBox_2)
        self.txtT2ArrayRow.setGeometry(QtCore.QRect(140, 80, 131, 20))
        self.txtT2ArrayRow.setInputMask("")
        self.txtT2ArrayRow.setObjectName("txtT2ArrayRow")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupNewConfig)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 280, 281, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.label_9.setObjectName("label_9")
        self.cmbT2CellType = QtWidgets.QComboBox(self.groupBox_3)
        self.cmbT2CellType.setGeometry(QtCore.QRect(70, 20, 111, 22))
        self.cmbT2CellType.setEditable(True)
        self.cmbT2CellType.setCurrentText("")
        self.cmbT2CellType.setObjectName("cmbT2CellType")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.label_10.setObjectName("label_10")
        self.txtT2WeightBits = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtT2WeightBits.setGeometry(QtCore.QRect(70, 50, 51, 20))
        self.txtT2WeightBits.setObjectName("txtT2WeightBits")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 80, 51, 16))
        self.label_11.setObjectName("label_11")
        self.txtT2CellBits = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtT2CellBits.setGeometry(QtCore.QRect(70, 80, 51, 20))
        self.txtT2CellBits.setObjectName("txtT2CellBits")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(190, 20, 31, 16))
        self.label_12.setObjectName("label_12")
        self.txtT2RMin = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtT2RMin.setGeometry(QtCore.QRect(220, 20, 41, 20))
        self.txtT2RMin.setObjectName("txtT2RMin")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(160, 50, 31, 20))
        self.label_13.setObjectName("label_13")
        self.txtT2RMax = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtT2RMax.setGeometry(QtCore.QRect(200, 50, 61, 20))
        self.txtT2RMax.setObjectName("txtT2RMax")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(130, 80, 71, 20))
        self.label_14.setObjectName("label_14")
        self.txtT2Voltage = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtT2Voltage.setGeometry(QtCore.QRect(200, 80, 61, 20))
        self.txtT2Voltage.setObjectName("txtT2Voltage")
        self.btnT2Default = QtWidgets.QPushButton(self.groupNewConfig)
        self.btnT2Default.setGeometry(QtCore.QRect(30, 430, 61, 23))
        self.btnT2Default.setObjectName("btnT2Default")
        self.btnT2Read = QtWidgets.QPushButton(self.groupNewConfig)
        self.btnT2Read.setGeometry(QtCore.QRect(100, 430, 61, 23))
        self.btnT2Read.setObjectName("btnT2Read")
        self.btnT2Save = QtWidgets.QPushButton(self.groupNewConfig)
        self.btnT2Save.setGeometry(QtCore.QRect(170, 430, 61, 23))
        self.btnT2Save.setObjectName("btnT2Save")
        self.btnT2Confirm1 = QtWidgets.QPushButton(self.groupNewConfig)
        self.btnT2Confirm1.setGeometry(QtCore.QRect(240, 430, 61, 23))
        self.btnT2Confirm1.setObjectName("btnT2Confirm1")
        self.groupBatConfig = QtWidgets.QGroupBox(self.tabconfig)
        self.groupBatConfig.setGeometry(QtCore.QRect(370, 20, 381, 481))
        self.groupBatConfig.setObjectName("groupBatConfig")
        self.btnT2ExportList = QtWidgets.QPushButton(self.groupBatConfig)
        self.btnT2ExportList.setGeometry(QtCore.QRect(290, 370, 75, 23))
        self.btnT2ExportList.setObjectName("btnT2ExportList")
        self.btnT2RemoveAll = QtWidgets.QPushButton(self.groupBatConfig)
        self.btnT2RemoveAll.setGeometry(QtCore.QRect(290, 340, 75, 23))
        self.btnT2RemoveAll.setObjectName("btnT2RemoveAll")
        self.btnT2Confirm2 = QtWidgets.QPushButton(self.groupBatConfig)
        self.btnT2Confirm2.setGeometry(QtCore.QRect(290, 430, 75, 23))
        self.btnT2Confirm2.setObjectName("btnT2Confirm2")
        self.btnT2RemoveFile = QtWidgets.QPushButton(self.groupBatConfig)
        self.btnT2RemoveFile.setGeometry(QtCore.QRect(290, 310, 75, 23))
        self.btnT2RemoveFile.setObjectName("btnT2RemoveFile")
        self.label_16 = QtWidgets.QLabel(self.groupBatConfig)
        self.label_16.setGeometry(QtCore.QRect(30, 42, 81, 20))
        self.label_16.setObjectName("label_16")
        self.btnT2AddFile = QtWidgets.QPushButton(self.groupBatConfig)
        self.btnT2AddFile.setGeometry(QtCore.QRect(290, 280, 75, 23))
        self.btnT2AddFile.setObjectName("btnT2AddFile")
        self.btnT2ImportList = QtWidgets.QPushButton(self.groupBatConfig)
        self.btnT2ImportList.setGeometry(QtCore.QRect(290, 400, 75, 23))
        self.btnT2ImportList.setObjectName("btnT2ImportList")
        self.lstT2ConfigList = QtWidgets.QListWidget(self.groupBatConfig)
        self.lstT2ConfigList.setGeometry(QtCore.QRect(30, 70, 251, 381))
        self.lstT2ConfigList.setObjectName("lstT2ConfigList")
        self.tabWidget.addTab(self.tabconfig, "")
        self.tabcase = QtWidgets.QWidget()
        self.tabcase.setObjectName("tabcase")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tabcase)
        self.groupBox_6.setGeometry(QtCore.QRect(30, 20, 721, 481))
        self.groupBox_6.setObjectName("groupBox_6")
        self.btnT3RemoveConfig = QtWidgets.QPushButton(self.groupBox_6)
        self.btnT3RemoveConfig.setGeometry(QtCore.QRect(610, 70, 75, 23))
        self.btnT3RemoveConfig.setObjectName("btnT3RemoveConfig")
        self.lstT3ConfigList = QtWidgets.QListWidget(self.groupBox_6)
        self.lstT3ConfigList.setGeometry(QtCore.QRect(280, 30, 321, 91))
        self.lstT3ConfigList.setObjectName("lstT3ConfigList")
        self.btnT3AddConfig = QtWidgets.QPushButton(self.groupBox_6)
        self.btnT3AddConfig.setGeometry(QtCore.QRect(610, 40, 75, 23))
        self.btnT3AddConfig.setObjectName("btnT3AddConfig")
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(280, 10, 81, 16))
        self.label_20.setObjectName("label_20")
        self.btnT3RemoveAllConfig = QtWidgets.QPushButton(self.groupBox_6)
        self.btnT3RemoveAllConfig.setGeometry(QtCore.QRect(610, 100, 75, 23))
        self.btnT3RemoveAllConfig.setObjectName("btnT3RemoveAllConfig")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_4.setGeometry(QtCore.QRect(280, 130, 401, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.txtT3BatchSize = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtT3BatchSize.setGeometry(QtCore.QRect(70, 20, 101, 20))
        self.txtT3BatchSize.setObjectName("txtT3BatchSize")
        self.txtT3OpenNet = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtT3OpenNet.setGeometry(QtCore.QRect(260, 20, 101, 20))
        self.txtT3OpenNet.setObjectName("txtT3OpenNet")
        self.txtT3EPoch = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtT3EPoch.setGeometry(QtCore.QRect(70, 60, 101, 20))
        self.txtT3EPoch.setObjectName("txtT3EPoch")
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(30, 60, 31, 16))
        self.label_25.setObjectName("label_25")
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.label_24.setObjectName("label_24")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(210, 20, 51, 16))
        self.label_23.setObjectName("label_23")
        self.btnT3OpenNet = QtWidgets.QPushButton(self.groupBox_4)
        self.btnT3OpenNet.setGeometry(QtCore.QRect(300, 50, 61, 23))
        self.btnT3OpenNet.setObjectName("btnT3OpenNet")
        self.btnT3PathSelection = QtWidgets.QPushButton(self.groupBox_4)
        self.btnT3PathSelection.setGeometry(QtCore.QRect(300, 110, 61, 23))
        self.btnT3PathSelection.setObjectName("btnT3PathSelection")
        self.txtT3OutputPath = QtWidgets.QLineEdit(self.groupBox_4)
        self.txtT3OutputPath.setGeometry(QtCore.QRect(260, 80, 101, 20))
        self.txtT3OutputPath.setObjectName("txtT3OutputPath")
        self.label_69 = QtWidgets.QLabel(self.groupBox_4)
        self.label_69.setGeometry(QtCore.QRect(210, 80, 51, 16))
        self.label_69.setObjectName("label_69")
        self.cmbT3NetType = QtWidgets.QComboBox(self.groupBox_4)
        self.cmbT3NetType.setGeometry(QtCore.QRect(70, 100, 101, 22))
        self.cmbT3NetType.setEditable(True)
        self.cmbT3NetType.setObjectName("cmbT3NetType")
        self.label_70 = QtWidgets.QLabel(self.groupBox_4)
        self.label_70.setGeometry(QtCore.QRect(20, 100, 51, 20))
        self.label_70.setObjectName("label_70")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_5.setGeometry(QtCore.QRect(590, 300, 111, 161))
        self.groupBox_5.setObjectName("groupBox_5")
        self.btnT3Confirm1 = QtWidgets.QPushButton(self.groupBox_5)
        self.btnT3Confirm1.setGeometry(QtCore.QRect(20, 110, 75, 23))
        self.btnT3Confirm1.setObjectName("btnT3Confirm1")
        self.btnT3LoadCase = QtWidgets.QPushButton(self.groupBox_5)
        self.btnT3LoadCase.setGeometry(QtCore.QRect(20, 30, 75, 23))
        self.btnT3LoadCase.setObjectName("btnT3LoadCase")
        self.btnT3SaveCase = QtWidgets.QPushButton(self.groupBox_5)
        self.btnT3SaveCase.setGeometry(QtCore.QRect(20, 70, 75, 23))
        self.btnT3SaveCase.setObjectName("btnT3SaveCase")
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_14.setGeometry(QtCore.QRect(10, 20, 261, 451))
        self.groupBox_14.setObjectName("groupBox_14")
        self.btnT3RemoveAllImage = QtWidgets.QPushButton(self.groupBox_14)
        self.btnT3RemoveAllImage.setGeometry(QtCore.QRect(180, 410, 71, 23))
        self.btnT3RemoveAllImage.setObjectName("btnT3RemoveAllImage")
        self.btnT3AddImage = QtWidgets.QPushButton(self.groupBox_14)
        self.btnT3AddImage.setGeometry(QtCore.QRect(20, 410, 71, 23))
        self.btnT3AddImage.setObjectName("btnT3AddImage")
        self.btnT3AddNet = QtWidgets.QPushButton(self.groupBox_14)
        self.btnT3AddNet.setGeometry(QtCore.QRect(20, 200, 75, 23))
        self.btnT3AddNet.setObjectName("btnT3AddNet")
        self.btnT3RemoveAllNet = QtWidgets.QPushButton(self.groupBox_14)
        self.btnT3RemoveAllNet.setGeometry(QtCore.QRect(180, 200, 75, 23))
        self.btnT3RemoveAllNet.setObjectName("btnT3RemoveAllNet")
        self.label_19 = QtWidgets.QLabel(self.groupBox_14)
        self.label_19.setGeometry(QtCore.QRect(20, 20, 121, 16))
        self.label_19.setObjectName("label_19")
        self.lstT3NetList = QtWidgets.QListWidget(self.groupBox_14)
        self.lstT3NetList.setGeometry(QtCore.QRect(20, 40, 231, 151))
        self.lstT3NetList.setObjectName("lstT3NetList")
        self.btnT3RemoveImage = QtWidgets.QPushButton(self.groupBox_14)
        self.btnT3RemoveImage.setGeometry(QtCore.QRect(100, 410, 71, 23))
        self.btnT3RemoveImage.setObjectName("btnT3RemoveImage")
        self.btnT3RemoveNet = QtWidgets.QPushButton(self.groupBox_14)
        self.btnT3RemoveNet.setGeometry(QtCore.QRect(100, 200, 75, 23))
        self.btnT3RemoveNet.setObjectName("btnT3RemoveNet")
        self.label_26 = QtWidgets.QLabel(self.groupBox_14)
        self.label_26.setGeometry(QtCore.QRect(20, 230, 111, 16))
        self.label_26.setObjectName("label_26")
        self.lstT3ImageList = QtWidgets.QListWidget(self.groupBox_14)
        self.lstT3ImageList.setGeometry(QtCore.QRect(20, 250, 231, 151))
        self.lstT3ImageList.setObjectName("lstT3ImageList")
        self.btnT3RemoveType = QtWidgets.QPushButton(self.groupBox_6)
        self.btnT3RemoveType.setGeometry(QtCore.QRect(510, 440, 61, 23))
        self.btnT3RemoveType.setObjectName("btnT3RemoveType")
        self.lstT3TypeList = QtWidgets.QListWidget(self.groupBox_6)
        self.lstT3TypeList.setGeometry(QtCore.QRect(440, 320, 131, 111))
        self.lstT3TypeList.setObjectName("lstT3TypeList")
        self.btnT3AddType = QtWidgets.QPushButton(self.groupBox_6)
        self.btnT3AddType.setGeometry(QtCore.QRect(440, 440, 61, 23))
        self.btnT3AddType.setObjectName("btnT3AddType")
        self.label_75 = QtWidgets.QLabel(self.groupBox_6)
        self.label_75.setGeometry(QtCore.QRect(450, 290, 51, 20))
        self.label_75.setObjectName("label_75")
        self.cmbT3NetType_2 = QtWidgets.QComboBox(self.groupBox_6)
        self.cmbT3NetType_2.setGeometry(QtCore.QRect(510, 290, 61, 22))
        self.cmbT3NetType_2.setEditable(True)
        self.cmbT3NetType_2.setObjectName("cmbT3NetType_2")
        self.btnT3RemoveSize = QtWidgets.QPushButton(self.groupBox_6)
        self.btnT3RemoveSize.setGeometry(QtCore.QRect(360, 440, 61, 23))
        self.btnT3RemoveSize.setObjectName("btnT3RemoveSize")
        self.btnT3AddSize = QtWidgets.QPushButton(self.groupBox_6)
        self.btnT3AddSize.setGeometry(QtCore.QRect(290, 440, 61, 23))
        self.btnT3AddSize.setObjectName("btnT3AddSize")
        self.txtT3BatchSize_3 = QtWidgets.QLineEdit(self.groupBox_6)
        self.txtT3BatchSize_3.setGeometry(QtCore.QRect(360, 290, 61, 20))
        self.txtT3BatchSize_3.setObjectName("txtT3BatchSize_3")
        self.lstT3SizeList = QtWidgets.QListWidget(self.groupBox_6)
        self.lstT3SizeList.setGeometry(QtCore.QRect(290, 320, 131, 111))
        self.lstT3SizeList.setObjectName("lstT3SizeList")
        self.label_76 = QtWidgets.QLabel(self.groupBox_6)
        self.label_76.setGeometry(QtCore.QRect(290, 290, 61, 20))
        self.label_76.setObjectName("label_76")
        self.tabWidget.addTab(self.tabcase, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.groupBox_8 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_8.setGeometry(QtCore.QRect(220, 260, 201, 231))
        self.groupBox_8.setObjectName("groupBox_8")
        self.lstT4ConfigList = QtWidgets.QListWidget(self.groupBox_8)
        self.lstT4ConfigList.setGeometry(QtCore.QRect(20, 30, 161, 181))
        self.lstT4ConfigList.setObjectName("lstT4ConfigList")
        self.groupBox_7 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 201, 231))
        self.groupBox_7.setObjectName("groupBox_7")
        self.lstT4NetList = QtWidgets.QListWidget(self.groupBox_7)
        self.lstT4NetList.setGeometry(QtCore.QRect(20, 30, 161, 181))
        self.lstT4NetList.setObjectName("lstT4NetList")
        self.groupBox_12 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_12.setGeometry(QtCore.QRect(230, 10, 331, 231))
        self.groupBox_12.setObjectName("groupBox_12")
        self.chkT4ArraySize = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkT4ArraySize.setGeometry(QtCore.QRect(30, 40, 91, 16))
        self.chkT4ArraySize.setChecked(True)
        self.chkT4ArraySize.setObjectName("chkT4ArraySize")
        self.chkT4Cores = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkT4Cores.setGeometry(QtCore.QRect(30, 70, 111, 16))
        self.chkT4Cores.setChecked(True)
        self.chkT4Cores.setObjectName("chkT4Cores")
        self.chkT4Area = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkT4Area.setGeometry(QtCore.QRect(30, 100, 101, 16))
        self.chkT4Area.setChecked(True)
        self.chkT4Area.setObjectName("chkT4Area")
        self.chkT4Energy = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkT4Energy.setGeometry(QtCore.QRect(30, 130, 141, 16))
        self.chkT4Energy.setChecked(True)
        self.chkT4Energy.setObjectName("chkT4Energy")
        self.chkT4Power = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkT4Power.setGeometry(QtCore.QRect(30, 160, 91, 16))
        self.chkT4Power.setChecked(True)
        self.chkT4Power.setObjectName("chkT4Power")
        self.chkT4Performance = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkT4Performance.setGeometry(QtCore.QRect(150, 40, 91, 16))
        self.chkT4Performance.setChecked(True)
        self.chkT4Performance.setObjectName("chkT4Performance")
        self.chkT4Accuracy = QtWidgets.QCheckBox(self.groupBox_12)
        self.chkT4Accuracy.setGeometry(QtCore.QRect(150, 70, 71, 16))
        self.chkT4Accuracy.setChecked(True)
        self.chkT4Accuracy.setObjectName("chkT4Accuracy")
        self.groupBox_13 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_13.setGeometry(QtCore.QRect(570, 10, 201, 221))
        self.groupBox_13.setObjectName("groupBox_13")
        self.txtT4Python = QtWidgets.QLineEdit(self.groupBox_13)
        self.txtT4Python.setGeometry(QtCore.QRect(20, 40, 161, 20))
        self.txtT4Python.setObjectName("txtT4Python")
        self.label_53 = QtWidgets.QLabel(self.groupBox_13)
        self.label_53.setGeometry(QtCore.QRect(20, 20, 121, 16))
        self.label_53.setObjectName("label_53")
        self.btnT4Python = QtWidgets.QPushButton(self.groupBox_13)
        self.btnT4Python.setGeometry(QtCore.QRect(110, 60, 75, 23))
        self.btnT4Python.setObjectName("btnT4Python")
        self.label_55 = QtWidgets.QLabel(self.groupBox_13)
        self.label_55.setGeometry(QtCore.QRect(20, 80, 101, 16))
        self.label_55.setObjectName("label_55")
        self.btnT4StartSimulation = QtWidgets.QPushButton(self.groupBox_13)
        self.btnT4StartSimulation.setGeometry(QtCore.QRect(50, 190, 101, 23))
        self.btnT4StartSimulation.setObjectName("btnT4StartSimulation")
        self.lstT4SizeList = QtWidgets.QListWidget(self.groupBox_13)
        self.lstT4SizeList.setGeometry(QtCore.QRect(20, 100, 161, 81))
        self.lstT4SizeList.setObjectName("lstT4SizeList")
        self.groupBox_9 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 260, 201, 231))
        self.groupBox_9.setObjectName("groupBox_9")
        self.lstT4ImageList = QtWidgets.QListWidget(self.groupBox_9)
        self.lstT4ImageList.setGeometry(QtCore.QRect(20, 30, 161, 181))
        self.lstT4ImageList.setObjectName("lstT4ImageList")
        self.groupBox_32 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_32.setGeometry(QtCore.QRect(430, 260, 131, 231))
        self.groupBox_32.setObjectName("groupBox_32")
        self.lstT4TypeList = QtWidgets.QListWidget(self.groupBox_32)
        self.lstT4TypeList.setGeometry(QtCore.QRect(20, 30, 91, 181))
        self.lstT4TypeList.setObjectName("lstT4TypeList")
        self.groupBox_15 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_15.setGeometry(QtCore.QRect(570, 230, 201, 261))
        self.groupBox_15.setObjectName("groupBox_15")
        self.txtT4BatchSize_2 = QtWidgets.QLineEdit(self.groupBox_15)
        self.txtT4BatchSize_2.setGeometry(QtCore.QRect(70, 20, 101, 20))
        self.txtT4BatchSize_2.setObjectName("txtT4BatchSize_2")
        self.txtT4OpenNet = QtWidgets.QLineEdit(self.groupBox_15)
        self.txtT4OpenNet.setGeometry(QtCore.QRect(70, 110, 101, 20))
        self.txtT4OpenNet.setObjectName("txtT4OpenNet")
        self.txtT4EPoch = QtWidgets.QLineEdit(self.groupBox_15)
        self.txtT4EPoch.setGeometry(QtCore.QRect(70, 50, 101, 20))
        self.txtT4EPoch.setObjectName("txtT4EPoch")
        self.label_28 = QtWidgets.QLabel(self.groupBox_15)
        self.label_28.setGeometry(QtCore.QRect(30, 50, 31, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_15)
        self.label_29.setGeometry(QtCore.QRect(10, 20, 61, 20))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_15)
        self.label_30.setGeometry(QtCore.QRect(10, 110, 61, 20))
        self.label_30.setObjectName("label_30")
        self.btnT4OpenNet = QtWidgets.QPushButton(self.groupBox_15)
        self.btnT4OpenNet.setGeometry(QtCore.QRect(110, 130, 61, 23))
        self.btnT4OpenNet.setObjectName("btnT4OpenNet")
        self.txtT4Output = QtWidgets.QLineEdit(self.groupBox_15)
        self.txtT4Output.setGeometry(QtCore.QRect(70, 160, 101, 20))
        self.txtT4Output.setObjectName("txtT4Output")
        self.btnT4Output = QtWidgets.QPushButton(self.groupBox_15)
        self.btnT4Output.setGeometry(QtCore.QRect(110, 180, 61, 23))
        self.btnT4Output.setObjectName("btnT4Output")
        self.label_31 = QtWidgets.QLabel(self.groupBox_15)
        self.label_31.setGeometry(QtCore.QRect(10, 160, 51, 16))
        self.label_31.setObjectName("label_31")
        self.cmbT4NetType = QtWidgets.QComboBox(self.groupBox_15)
        self.cmbT4NetType.setGeometry(QtCore.QRect(70, 80, 101, 22))
        self.cmbT4NetType.setEditable(True)
        self.cmbT4NetType.setObjectName("cmbT4NetType")
        self.label_32 = QtWidgets.QLabel(self.groupBox_15)
        self.label_32.setGeometry(QtCore.QRect(20, 80, 51, 20))
        self.label_32.setObjectName("label_32")
        self.btnT4StartTrain = QtWidgets.QPushButton(self.groupBox_15)
        self.btnT4StartTrain.setGeometry(QtCore.QRect(50, 230, 101, 23))
        self.btnT4StartTrain.setObjectName("btnT4StartTrain")
        self.chkT4auto = QtWidgets.QCheckBox(self.groupBox_15)
        self.chkT4auto.setGeometry(QtCore.QRect(30, 210, 151, 20))
        self.chkT4auto.setChecked(True)
        self.chkT4auto.setObjectName("chkT4auto")
        self.tabWidget.addTab(self.widget, "")
        self.tabresult = QtWidgets.QWidget()
        self.tabresult.setObjectName("tabresult")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tabresult)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 20, 361, 481))
        self.groupBox_10.setObjectName("groupBox_10")
        self.btnT5SaveResult = QtWidgets.QPushButton(self.groupBox_10)
        self.btnT5SaveResult.setGeometry(QtCore.QRect(260, 430, 61, 23))
        self.btnT5SaveResult.setObjectName("btnT5SaveResult")
        self.txtT5Result = QtWidgets.QTextBrowser(self.groupBox_10)
        self.txtT5Result.setGeometry(QtCore.QRect(40, 40, 281, 381))
        self.txtT5Result.setObjectName("txtT5Result")
        self.btnT5Stop = QtWidgets.QPushButton(self.groupBox_10)
        self.btnT5Stop.setGeometry(QtCore.QRect(190, 430, 61, 23))
        self.btnT5Stop.setObjectName("btnT5Stop")
        self.btnT5ShowProcess = QtWidgets.QPushButton(self.groupBox_10)
        self.btnT5ShowProcess.setGeometry(QtCore.QRect(120, 430, 61, 23))
        self.btnT5ShowProcess.setObjectName("btnT5ShowProcess")
        self.btnT5Clear = QtWidgets.QPushButton(self.groupBox_10)
        self.btnT5Clear.setGeometry(QtCore.QRect(50, 430, 61, 23))
        self.btnT5Clear.setObjectName("btnT5Clear")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tabresult)
        self.groupBox_11.setGeometry(QtCore.QRect(390, 20, 361, 481))
        self.groupBox_11.setObjectName("groupBox_11")
        self.btnT5SaveAnalysis = QtWidgets.QPushButton(self.groupBox_11)
        self.btnT5SaveAnalysis.setGeometry(QtCore.QRect(240, 430, 75, 23))
        self.btnT5SaveAnalysis.setObjectName("btnT5SaveAnalysis")
        self.btnT5ShowAnalysis = QtWidgets.QPushButton(self.groupBox_11)
        self.btnT5ShowAnalysis.setGeometry(QtCore.QRect(50, 430, 75, 23))
        self.btnT5ShowAnalysis.setObjectName("btnT5ShowAnalysis")
        self.txtT5Analysis = QtWidgets.QTextBrowser(self.groupBox_11)
        self.txtT5Analysis.setGeometry(QtCore.QRect(40, 40, 281, 381))
        self.txtT5Analysis.setObjectName("txtT5Analysis")
        self.tabWidget.addTab(self.tabresult, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 835, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.cmbT2DO.setCurrentIndex(-1)
        self.cmbT2CellType.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupTrain.setTitle(_translate("MainWindow", "训练网络"))
        self.label.setText(_translate("MainWindow", "选择网络"))
        self.btnT1OpenNet.setText(_translate("MainWindow", "打开文件"))
        self.label_17.setText(_translate("MainWindow", "Batch Size"))
        self.label_18.setText(_translate("MainWindow", "EPoch"))
        self.btnT1confirm1.setText(_translate("MainWindow", "确定"))
        self.btnT1PathSelection.setText(_translate("MainWindow", "选择路径"))
        self.label_71.setText(_translate("MainWindow", "网络类型"))
        self.label_72.setText(_translate("MainWindow", "输出位置"))
        self.groupBatNet.setTitle(_translate("MainWindow", "批量网络文件设置"))
        self.btnT1RemoveFile.setText(_translate("MainWindow", "删除文件"))
        self.btnT1AddFile.setText(_translate("MainWindow", "添加文件"))
        self.label_15.setText(_translate("MainWindow", "Weights文件列表.npz"))
        self.btnT1confirm2.setText(_translate("MainWindow", "确定"))
        self.btnT1RemoveAll.setText(_translate("MainWindow", "清空列表"))
        self.btnT1ExportList.setText(_translate("MainWindow", "导出列表"))
        self.btnT1ImportList.setText(_translate("MainWindow", "读取列表"))
        self.btnT1confirm3.setText(_translate("MainWindow", "确定"))
        self.label_21.setText(_translate("MainWindow", "Image文件列表.npy"))
        self.btnT1AddFile_2.setText(_translate("MainWindow", "添加文件"))
        self.btnT1RemoveAll_2.setText(_translate("MainWindow", "清空列表"))
        self.btnT1ExportList_2.setText(_translate("MainWindow", "导出列表"))
        self.btnT1ImportList_2.setText(_translate("MainWindow", "读取列表"))
        self.btnT1RemoveFile_2.setText(_translate("MainWindow", "删除文件"))
        self.groupBox_31.setTitle(_translate("MainWindow", "批量参数设置"))
        self.label_73.setText(_translate("MainWindow", "网络类型"))
        self.btnT1RemoveType.setText(_translate("MainWindow", "删除类型"))
        self.btnT1AddType.setText(_translate("MainWindow", "添加类型"))
        self.btnT1RemoveSize.setText(_translate("MainWindow", "删除Size"))
        self.label_22.setText(_translate("MainWindow", "Batch Size"))
        self.btnT1AddSize.setText(_translate("MainWindow", "添加Size"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabnet), _translate("MainWindow", "Net"))
        self.groupNewConfig.setTitle(_translate("MainWindow", "设置新的配置文件"))
        self.groupBox.setTitle(_translate("MainWindow", "System Parameters"))
        self.label_3.setText(_translate("MainWindow", "DesignOptimization"))
        self.label_4.setText(_translate("MainWindow", "numCoreVMax"))
        self.txtT2CoreVMax.setText(_translate("MainWindow", "20"))
        self.label_5.setText(_translate("MainWindow", "numCoreHMax"))
        self.txtT2CoreHMax.setText(_translate("MainWindow", "20"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Core Parameters"))
        self.label_6.setText(_translate("MainWindow", "IOBits"))
        self.txtT2IOBits.setText(_translate("MainWindow", "8"))
        self.label_7.setText(_translate("MainWindow", "numArrayCol"))
        self.txtT2ArrayCol.setText(_translate("MainWindow", "256"))
        self.label_8.setText(_translate("MainWindow", "numArrayRow "))
        self.txtT2ArrayRow.setText(_translate("MainWindow", "256"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Cell Parameters"))
        self.label_9.setText(_translate("MainWindow", "CellType"))
        self.label_10.setText(_translate("MainWindow", "WeightBits"))
        self.txtT2WeightBits.setText(_translate("MainWindow", "8"))
        self.label_11.setText(_translate("MainWindow", "CellBits"))
        self.txtT2CellBits.setText(_translate("MainWindow", "4"))
        self.label_12.setText(_translate("MainWindow", "Rmin"))
        self.txtT2RMin.setText(_translate("MainWindow", "25e3"))
        self.label_13.setText(_translate("MainWindow", "Rmax"))
        self.txtT2RMax.setText(_translate("MainWindow", "265e3"))
        self.label_14.setText(_translate("MainWindow", "ReadVoltage"))
        self.txtT2Voltage.setText(_translate("MainWindow", "0.15"))
        self.btnT2Default.setText(_translate("MainWindow", "恢复默认"))
        self.btnT2Read.setText(_translate("MainWindow", "读取配置"))
        self.btnT2Save.setText(_translate("MainWindow", "保存配置"))
        self.btnT2Confirm1.setText(_translate("MainWindow", "确定"))
        self.groupBatConfig.setTitle(_translate("MainWindow", "批量配置文件设置"))
        self.btnT2ExportList.setText(_translate("MainWindow", "导出列表"))
        self.btnT2RemoveAll.setText(_translate("MainWindow", "清空列表"))
        self.btnT2Confirm2.setText(_translate("MainWindow", "确定"))
        self.btnT2RemoveFile.setText(_translate("MainWindow", "删除文件"))
        self.label_16.setText(_translate("MainWindow", "配置文件列表"))
        self.btnT2AddFile.setText(_translate("MainWindow", "添加文件"))
        self.btnT2ImportList.setText(_translate("MainWindow", "读取列表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabconfig), _translate("MainWindow", "Config"))
        self.groupBox_6.setTitle(_translate("MainWindow", "用例设定"))
        self.btnT3RemoveConfig.setText(_translate("MainWindow", "删除"))
        self.btnT3AddConfig.setText(_translate("MainWindow", "添加"))
        self.label_20.setText(_translate("MainWindow", "配置文件列表"))
        self.btnT3RemoveAllConfig.setText(_translate("MainWindow", "清空列表"))
        self.groupBox_4.setTitle(_translate("MainWindow", "训练网络"))
        self.label_25.setText(_translate("MainWindow", "EPoch"))
        self.label_24.setText(_translate("MainWindow", "Batch Size"))
        self.label_23.setText(_translate("MainWindow", "选择网络"))
        self.btnT3OpenNet.setText(_translate("MainWindow", "打开文件"))
        self.btnT3PathSelection.setText(_translate("MainWindow", "选择路径"))
        self.label_69.setText(_translate("MainWindow", "输出位置"))
        self.label_70.setText(_translate("MainWindow", "网络类型"))
        self.groupBox_5.setTitle(_translate("MainWindow", "用例设置"))
        self.btnT3Confirm1.setText(_translate("MainWindow", "确定"))
        self.btnT3LoadCase.setText(_translate("MainWindow", "读取用例"))
        self.btnT3SaveCase.setText(_translate("MainWindow", "保存用例"))
        self.groupBox_14.setTitle(_translate("MainWindow", "网络文件设置"))
        self.btnT3RemoveAllImage.setText(_translate("MainWindow", "清空列表"))
        self.btnT3AddImage.setText(_translate("MainWindow", "添加"))
        self.btnT3AddNet.setText(_translate("MainWindow", "添加"))
        self.btnT3RemoveAllNet.setText(_translate("MainWindow", "清空列表"))
        self.label_19.setText(_translate("MainWindow", "Weights文件列表.npz"))
        self.btnT3RemoveImage.setText(_translate("MainWindow", "删除"))
        self.btnT3RemoveNet.setText(_translate("MainWindow", "删除"))
        self.label_26.setText(_translate("MainWindow", "Image文件列表.npy"))
        self.btnT3RemoveType.setText(_translate("MainWindow", "删除类型"))
        self.btnT3AddType.setText(_translate("MainWindow", "添加类型"))
        self.label_75.setText(_translate("MainWindow", "网络类型"))
        self.btnT3RemoveSize.setText(_translate("MainWindow", "删除Size"))
        self.btnT3AddSize.setText(_translate("MainWindow", "添加Size"))
        self.label_76.setText(_translate("MainWindow", "Batch Size"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabcase), _translate("MainWindow", "TestCase"))
        self.groupBox_8.setTitle(_translate("MainWindow", "配置文件信息"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Weight文件信息.npz"))
        self.groupBox_12.setTitle(_translate("MainWindow", "结果分析选项"))
        self.chkT4ArraySize.setText(_translate("MainWindow", "Array Size"))
        self.chkT4Cores.setText(_translate("MainWindow", "Number of Cores"))
        self.chkT4Area.setText(_translate("MainWindow", "Area"))
        self.chkT4Energy.setText(_translate("MainWindow", "Read Dynamic Energy"))
        self.chkT4Power.setText(_translate("MainWindow", "Read Power"))
        self.chkT4Performance.setText(_translate("MainWindow", "Performance"))
        self.chkT4Accuracy.setText(_translate("MainWindow", "Accuracy"))
        self.groupBox_13.setTitle(_translate("MainWindow", "硬件模拟"))
        self.txtT4Python.setText(_translate("MainWindow", "C:/python27"))
        self.label_53.setText(_translate("MainWindow", "Python27/python.exe"))
        self.btnT4Python.setText(_translate("MainWindow", "选择文件"))
        self.label_55.setText(_translate("MainWindow", "Batch Size List"))
        self.btnT4StartSimulation.setText(_translate("MainWindow", "开始硬件模拟"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Image文件信息.npy"))
        self.groupBox_32.setTitle(_translate("MainWindow", "网络类型列表"))
        self.groupBox_15.setTitle(_translate("MainWindow", "训练网络"))
        self.label_28.setText(_translate("MainWindow", "EPoch"))
        self.label_29.setText(_translate("MainWindow", "Batch Size"))
        self.label_30.setText(_translate("MainWindow", "原网络路径"))
        self.btnT4OpenNet.setText(_translate("MainWindow", "打开文件"))
        self.btnT4Output.setText(_translate("MainWindow", "选择路径"))
        self.label_31.setText(_translate("MainWindow", "输出位置"))
        self.label_32.setText(_translate("MainWindow", "网络类型"))
        self.btnT4StartTrain.setText(_translate("MainWindow", "开始训练网络"))
        self.chkT4auto.setText(_translate("MainWindow", "训练完成后直接开始模拟"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "Hardware Simulation"))
        self.groupBox_10.setTitle(_translate("MainWindow", "结果显示"))
        self.btnT5SaveResult.setText(_translate("MainWindow", "保存结果"))
        self.btnT5Stop.setText(_translate("MainWindow", "结束进程"))
        self.btnT5ShowProcess.setText(_translate("MainWindow", "进程情况"))
        self.btnT5Clear.setText(_translate("MainWindow", "清空窗口"))
        self.groupBox_11.setTitle(_translate("MainWindow", "分析显示"))
        self.btnT5SaveAnalysis.setText(_translate("MainWindow", "保存分析"))
        self.btnT5ShowAnalysis.setText(_translate("MainWindow", "分析结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabresult), _translate("MainWindow", "Result"))

