# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\simulatorProject\前期文档\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(835, 628)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 791, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.tabnet = QtWidgets.QWidget()
        self.tabnet.setObjectName("tabnet")
        self.groupTrain = QtWidgets.QGroupBox(self.tabnet)
        self.groupTrain.setGeometry(QtCore.QRect(30, 20, 321, 231))
        self.groupTrain.setObjectName("groupTrain")
        self.label = QtWidgets.QLabel(self.groupTrain)
        self.label.setGeometry(QtCore.QRect(10, 40, 54, 12))
        self.label.setObjectName("label")
        self.txtT1OpenNet = QtWidgets.QLineEdit(self.groupTrain)
        self.txtT1OpenNet.setGeometry(QtCore.QRect(60, 40, 161, 20))
        self.txtT1OpenNet.setObjectName("txtT1OpenNet")
        self.btnT1OpenNet = QtWidgets.QPushButton(self.groupTrain)
        self.btnT1OpenNet.setGeometry(QtCore.QRect(230, 40, 61, 23))
        self.btnT1OpenNet.setObjectName("btnT1OpenNet")
        self.label_17 = QtWidgets.QLabel(self.groupTrain)
        self.label_17.setGeometry(QtCore.QRect(10, 80, 61, 20))
        self.label_17.setObjectName("label_17")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupTrain)
        self.lineEdit_13.setGeometry(QtCore.QRect(80, 80, 141, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_18 = QtWidgets.QLabel(self.groupTrain)
        self.label_18.setGeometry(QtCore.QRect(40, 120, 31, 16))
        self.label_18.setObjectName("label_18")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupTrain)
        self.lineEdit_14.setGeometry(QtCore.QRect(80, 120, 141, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.btnT1confirm1 = QtWidgets.QPushButton(self.groupTrain)
        self.btnT1confirm1.setGeometry(QtCore.QRect(220, 190, 75, 23))
        self.btnT1confirm1.setObjectName("btnT1confirm1")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.groupTrain)
        self.lineEdit_18.setGeometry(QtCore.QRect(60, 160, 161, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.label_26 = QtWidgets.QLabel(self.groupTrain)
        self.label_26.setGeometry(QtCore.QRect(10, 160, 54, 12))
        self.label_26.setObjectName("label_26")
        self.groupBatNet = QtWidgets.QGroupBox(self.tabnet)
        self.groupBatNet.setGeometry(QtCore.QRect(370, 20, 381, 481))
        self.groupBatNet.setObjectName("groupBatNet")
        self.btnT1RemoveFile = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1RemoveFile.setGeometry(QtCore.QRect(290, 310, 75, 23))
        self.btnT1RemoveFile.setObjectName("btnT1RemoveFile")
        self.btnT1AddFile = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1AddFile.setGeometry(QtCore.QRect(290, 280, 75, 23))
        self.btnT1AddFile.setObjectName("btnT1AddFile")
        self.label_15 = QtWidgets.QLabel(self.groupBatNet)
        self.label_15.setGeometry(QtCore.QRect(30, 42, 91, 20))
        self.label_15.setObjectName("label_15")
        self.btnT1confirm3 = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1confirm3.setGeometry(QtCore.QRect(290, 430, 75, 23))
        self.btnT1confirm3.setObjectName("btnT1confirm3")
        self.btnT1RemoveAll = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1RemoveAll.setGeometry(QtCore.QRect(290, 340, 75, 23))
        self.btnT1RemoveAll.setObjectName("btnT1RemoveAll")
        self.btnT1ExportList = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1ExportList.setGeometry(QtCore.QRect(290, 370, 75, 23))
        self.btnT1ExportList.setObjectName("btnT1ExportList")
        self.btnT1ImportList = QtWidgets.QPushButton(self.groupBatNet)
        self.btnT1ImportList.setGeometry(QtCore.QRect(290, 400, 75, 23))
        self.btnT1ImportList.setObjectName("btnT1ImportList")
        self.lstT1NetList = QtWidgets.QListWidget(self.groupBatNet)
        self.lstT1NetList.setGeometry(QtCore.QRect(30, 70, 251, 381))
        self.lstT1NetList.setObjectName("lstT1NetList")
        self.groupImportNet = QtWidgets.QGroupBox(self.tabnet)
        self.groupImportNet.setGeometry(QtCore.QRect(30, 260, 321, 241))
        self.groupImportNet.setObjectName("groupImportNet")
        self.label_2 = QtWidgets.QLabel(self.groupImportNet)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 54, 12))
        self.label_2.setObjectName("label_2")
        self.btnT1ImportNet = QtWidgets.QPushButton(self.groupImportNet)
        self.btnT1ImportNet.setGeometry(QtCore.QRect(240, 40, 61, 23))
        self.btnT1ImportNet.setObjectName("btnT1ImportNet")
        self.txtT1ImportNet = QtWidgets.QLineEdit(self.groupImportNet)
        self.txtT1ImportNet.setGeometry(QtCore.QRect(70, 40, 161, 20))
        self.txtT1ImportNet.setObjectName("txtT1ImportNet")
        self.btnT1confirm2 = QtWidgets.QPushButton(self.groupImportNet)
        self.btnT1confirm2.setGeometry(QtCore.QRect(220, 180, 75, 23))
        self.btnT1confirm2.setObjectName("btnT1confirm2")
        self.tabWidget.addTab(self.tabnet, "")
        self.tabconfig = QtWidgets.QWidget()
        self.tabconfig.setObjectName("tabconfig")
        self.groupNewConfig = QtWidgets.QGroupBox(self.tabconfig)
        self.groupNewConfig.setGeometry(QtCore.QRect(30, 20, 321, 481))
        self.groupNewConfig.setObjectName("groupNewConfig")
        self.groupBox = QtWidgets.QGroupBox(self.groupNewConfig)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 281, 121))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(138, 20, 131, 22))
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(50, 50, 71, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 50, 131, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(50, 80, 71, 20))
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(140, 80, 131, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupNewConfig)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 150, 281, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(70, 20, 41, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(140, 20, 131, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(40, 50, 71, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(140, 50, 131, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(40, 80, 71, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(140, 80, 131, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupNewConfig)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 280, 281, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(20, 20, 51, 16))
        self.label_9.setObjectName("label_9")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_2.setGeometry(QtCore.QRect(80, 20, 81, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 61, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(80, 50, 41, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(20, 80, 51, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(80, 80, 41, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(170, 20, 31, 16))
        self.label_12.setObjectName("label_12")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_10.setGeometry(QtCore.QRect(210, 20, 51, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(170, 50, 31, 20))
        self.label_13.setObjectName("label_13")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(210, 50, 51, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(130, 80, 71, 20))
        self.label_14.setObjectName("label_14")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_12.setGeometry(QtCore.QRect(200, 80, 61, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupNewConfig)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 430, 61, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupNewConfig)
        self.pushButton_7.setGeometry(QtCore.QRect(100, 430, 61, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupNewConfig)
        self.pushButton_8.setGeometry(QtCore.QRect(170, 430, 61, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupNewConfig)
        self.pushButton_9.setGeometry(QtCore.QRect(240, 430, 61, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.groupBatConfig = QtWidgets.QGroupBox(self.tabconfig)
        self.groupBatConfig.setGeometry(QtCore.QRect(370, 20, 381, 481))
        self.groupBatConfig.setObjectName("groupBatConfig")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBatConfig)
        self.pushButton_12.setGeometry(QtCore.QRect(290, 370, 75, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBatConfig)
        self.pushButton_13.setGeometry(QtCore.QRect(290, 340, 75, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBatConfig)
        self.pushButton_14.setGeometry(QtCore.QRect(290, 430, 75, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBatConfig)
        self.pushButton_15.setGeometry(QtCore.QRect(290, 310, 75, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.label_16 = QtWidgets.QLabel(self.groupBatConfig)
        self.label_16.setGeometry(QtCore.QRect(30, 42, 81, 20))
        self.label_16.setObjectName("label_16")
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBatConfig)
        self.pushButton_16.setGeometry(QtCore.QRect(290, 280, 75, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBatConfig)
        self.pushButton_17.setGeometry(QtCore.QRect(290, 400, 75, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBatConfig)
        self.listWidget_2.setGeometry(QtCore.QRect(30, 70, 251, 381))
        self.listWidget_2.setObjectName("listWidget_2")
        self.tabWidget.addTab(self.tabconfig, "")
        self.tabcase = QtWidgets.QWidget()
        self.tabcase.setObjectName("tabcase")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabcase)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 20, 321, 231))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(30, 20, 101, 16))
        self.label_19.setObjectName("label_19")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_19.setGeometry(QtCore.QRect(200, 40, 75, 23))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_20.setGeometry(QtCore.QRect(200, 70, 75, 23))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_22.setGeometry(QtCore.QRect(200, 100, 75, 23))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_23.setGeometry(QtCore.QRect(200, 180, 75, 23))
        self.pushButton_23.setObjectName("pushButton_23")
        self.listWidget_3 = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidget_3.setGeometry(QtCore.QRect(30, 40, 151, 171))
        self.listWidget_3.setObjectName("listWidget_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabcase)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 270, 321, 231))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_24.setGeometry(QtCore.QRect(200, 180, 75, 23))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_25.setGeometry(QtCore.QRect(200, 40, 75, 23))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_26.setGeometry(QtCore.QRect(200, 100, 75, 23))
        self.pushButton_26.setObjectName("pushButton_26")
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(30, 20, 81, 16))
        self.label_20.setObjectName("label_20")
        self.pushButton_27 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_27.setGeometry(QtCore.QRect(200, 70, 75, 23))
        self.pushButton_27.setObjectName("pushButton_27")
        self.listWidget_4 = QtWidgets.QListWidget(self.groupBox_5)
        self.listWidget_4.setGeometry(QtCore.QRect(30, 40, 151, 171))
        self.listWidget_4.setObjectName("listWidget_4")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tabcase)
        self.groupBox_6.setGeometry(QtCore.QRect(370, 20, 381, 481))
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton_30 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_30.setGeometry(QtCore.QRect(90, 230, 75, 23))
        self.pushButton_30.setObjectName("pushButton_30")
        self.label_21 = QtWidgets.QLabel(self.groupBox_6)
        self.label_21.setGeometry(QtCore.QRect(10, 30, 101, 16))
        self.label_21.setObjectName("label_21")
        self.pushButton_32 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_32.setGeometry(QtCore.QRect(10, 230, 75, 23))
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_33.setGeometry(QtCore.QRect(190, 230, 75, 23))
        self.pushButton_33.setObjectName("pushButton_33")
        self.label_22 = QtWidgets.QLabel(self.groupBox_6)
        self.label_22.setGeometry(QtCore.QRect(190, 30, 81, 16))
        self.label_22.setObjectName("label_22")
        self.pushButton_36 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_36.setGeometry(QtCore.QRect(270, 230, 75, 23))
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_37 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_37.setGeometry(QtCore.QRect(270, 340, 75, 23))
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_38.setGeometry(QtCore.QRect(270, 370, 75, 23))
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_39.setGeometry(QtCore.QRect(270, 400, 75, 23))
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_40.setGeometry(QtCore.QRect(270, 430, 75, 23))
        self.pushButton_40.setObjectName("pushButton_40")
        self.label_25 = QtWidgets.QLabel(self.groupBox_6)
        self.label_25.setGeometry(QtCore.QRect(40, 360, 31, 16))
        self.label_25.setObjectName("label_25")
        self.label_23 = QtWidgets.QLabel(self.groupBox_6)
        self.label_23.setGeometry(QtCore.QRect(10, 280, 54, 12))
        self.label_23.setObjectName("label_23")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_15.setGeometry(QtCore.QRect(60, 280, 161, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_16.setGeometry(QtCore.QRect(80, 360, 141, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_24 = QtWidgets.QLabel(self.groupBox_6)
        self.label_24.setGeometry(QtCore.QRect(10, 320, 61, 20))
        self.label_24.setObjectName("label_24")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_17.setGeometry(QtCore.QRect(80, 320, 141, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.pushButton_29 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_29.setGeometry(QtCore.QRect(230, 280, 61, 23))
        self.pushButton_29.setObjectName("pushButton_29")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_19.setGeometry(QtCore.QRect(60, 400, 161, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_27 = QtWidgets.QLabel(self.groupBox_6)
        self.label_27.setGeometry(QtCore.QRect(10, 400, 54, 12))
        self.label_27.setObjectName("label_27")
        self.listWidget_5 = QtWidgets.QListWidget(self.groupBox_6)
        self.listWidget_5.setGeometry(QtCore.QRect(10, 50, 151, 171))
        self.listWidget_5.setObjectName("listWidget_5")
        self.listWidget_6 = QtWidgets.QListWidget(self.groupBox_6)
        self.listWidget_6.setGeometry(QtCore.QRect(190, 50, 151, 171))
        self.listWidget_6.setObjectName("listWidget_6")
        self.tabWidget.addTab(self.tabcase, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.groupBox_8 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_8.setGeometry(QtCore.QRect(30, 270, 321, 231))
        self.groupBox_8.setObjectName("groupBox_8")
        self.listView_8 = QtWidgets.QListView(self.groupBox_8)
        self.listView_8.setGeometry(QtCore.QRect(30, 30, 261, 181))
        self.listView_8.setObjectName("listView_8")
        self.groupBox_7 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_7.setGeometry(QtCore.QRect(30, 20, 321, 231))
        self.groupBox_7.setObjectName("groupBox_7")
        self.listView_7 = QtWidgets.QListView(self.groupBox_7)
        self.listView_7.setGeometry(QtCore.QRect(30, 30, 261, 181))
        self.listView_7.setObjectName("listView_7")
        self.groupBox_9 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_9.setGeometry(QtCore.QRect(370, 20, 381, 481))
        self.groupBox_9.setObjectName("groupBox_9")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_12.setGeometry(QtCore.QRect(30, 30, 321, 201))
        self.groupBox_12.setObjectName("groupBox_12")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox.setGeometry(QtCore.QRect(30, 30, 71, 16))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_2.setGeometry(QtCore.QRect(30, 60, 71, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_3.setGeometry(QtCore.QRect(30, 90, 71, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_4.setGeometry(QtCore.QRect(30, 120, 71, 16))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_5.setGeometry(QtCore.QRect(30, 150, 71, 16))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_6.setGeometry(QtCore.QRect(150, 120, 71, 16))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_7.setGeometry(QtCore.QRect(150, 150, 71, 16))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_8.setGeometry(QtCore.QRect(150, 30, 71, 16))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_9.setGeometry(QtCore.QRect(150, 90, 71, 16))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_10.setGeometry(QtCore.QRect(150, 60, 71, 16))
        self.checkBox_10.setObjectName("checkBox_10")
        self.pushButton_35 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_35.setGeometry(QtCore.QRect(230, 160, 75, 23))
        self.pushButton_35.setObjectName("pushButton_35")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_13.setGeometry(QtCore.QRect(30, 250, 321, 201))
        self.groupBox_13.setObjectName("groupBox_13")
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_11.setGeometry(QtCore.QRect(150, 30, 71, 16))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_12.setGeometry(QtCore.QRect(150, 120, 71, 16))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_13.setGeometry(QtCore.QRect(30, 150, 71, 16))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_14.setGeometry(QtCore.QRect(150, 90, 71, 16))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_15.setGeometry(QtCore.QRect(30, 30, 71, 16))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_16.setGeometry(QtCore.QRect(30, 90, 71, 16))
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_17.setGeometry(QtCore.QRect(30, 60, 71, 16))
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_18.setGeometry(QtCore.QRect(150, 150, 71, 16))
        self.checkBox_18.setObjectName("checkBox_18")
        self.checkBox_19 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_19.setGeometry(QtCore.QRect(30, 120, 71, 16))
        self.checkBox_19.setObjectName("checkBox_19")
        self.checkBox_20 = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkBox_20.setGeometry(QtCore.QRect(150, 60, 71, 16))
        self.checkBox_20.setObjectName("checkBox_20")
        self.pushButton_41 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_41.setGeometry(QtCore.QRect(230, 160, 75, 23))
        self.pushButton_41.setObjectName("pushButton_41")
        self.tabWidget.addTab(self.widget, "")
        self.tabresult = QtWidgets.QWidget()
        self.tabresult.setObjectName("tabresult")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tabresult)
        self.groupBox_10.setGeometry(QtCore.QRect(30, 20, 321, 481))
        self.groupBox_10.setObjectName("groupBox_10")
        self.listView_9 = QtWidgets.QListView(self.groupBox_10)
        self.listView_9.setGeometry(QtCore.QRect(30, 40, 251, 381))
        self.listView_9.setObjectName("listView_9")
        self.pushButton_31 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_31.setGeometry(QtCore.QRect(210, 430, 75, 23))
        self.pushButton_31.setObjectName("pushButton_31")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tabresult)
        self.groupBox_11.setGeometry(QtCore.QRect(370, 20, 381, 481))
        self.groupBox_11.setObjectName("groupBox_11")
        self.listView_10 = QtWidgets.QListView(self.groupBox_11)
        self.listView_10.setGeometry(QtCore.QRect(40, 40, 311, 381))
        self.listView_10.setObjectName("listView_10")
        self.pushButton_34 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_34.setGeometry(QtCore.QRect(280, 430, 75, 23))
        self.pushButton_34.setObjectName("pushButton_34")
        self.tabWidget.addTab(self.tabresult, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 835, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupTrain.setTitle(_translate("MainWindow", "训练网络"))
        self.label.setText(_translate("MainWindow", "选择网络"))
        self.btnT1OpenNet.setText(_translate("MainWindow", "打开文件"))
        self.label_17.setText(_translate("MainWindow", "Batch Size"))
        self.label_18.setText(_translate("MainWindow", "EPoch"))
        self.btnT1confirm1.setText(_translate("MainWindow", "确定"))
        self.label_26.setText(_translate("MainWindow", "生成路径"))
        self.groupBatNet.setTitle(_translate("MainWindow", "批量网络处理"))
        self.btnT1RemoveFile.setText(_translate("MainWindow", "删除文件"))
        self.btnT1AddFile.setText(_translate("MainWindow", "添加文件"))
        self.label_15.setText(_translate("MainWindow", "网络文件列表"))
        self.btnT1confirm3.setText(_translate("MainWindow", "确定"))
        self.btnT1RemoveAll.setText(_translate("MainWindow", "清空列表"))
        self.btnT1ExportList.setText(_translate("MainWindow", "导出列表"))
        self.btnT1ImportList.setText(_translate("MainWindow", "读取列表"))
        self.groupImportNet.setTitle(_translate("MainWindow", "导入现有网络数据"))
        self.label_2.setText(_translate("MainWindow", "导入网络"))
        self.btnT1ImportNet.setText(_translate("MainWindow", "打开文件"))
        self.btnT1confirm2.setText(_translate("MainWindow", "确定"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabnet), _translate("MainWindow", "Net"))
        self.groupNewConfig.setTitle(_translate("MainWindow", "设置新的配置文件"))
        self.groupBox.setTitle(_translate("MainWindow", "System Parameters"))
        self.label_3.setText(_translate("MainWindow", "DesignOptimization"))
        self.label_4.setText(_translate("MainWindow", "numCoreVMax"))
        self.label_5.setText(_translate("MainWindow", "numCoreHMax"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Core Parameters"))
        self.label_6.setText(_translate("MainWindow", "IOBits"))
        self.label_7.setText(_translate("MainWindow", "numArrayCol"))
        self.label_8.setText(_translate("MainWindow", "numArrayRow "))
        self.groupBox_3.setTitle(_translate("MainWindow", "Cell Parameters"))
        self.label_9.setText(_translate("MainWindow", "CellType"))
        self.label_10.setText(_translate("MainWindow", "WeightBits"))
        self.label_11.setText(_translate("MainWindow", "CellBits"))
        self.label_12.setText(_translate("MainWindow", "Rmin"))
        self.label_13.setText(_translate("MainWindow", "Rmax"))
        self.label_14.setText(_translate("MainWindow", "ReadVoltage"))
        self.pushButton_6.setText(_translate("MainWindow", "恢复默认"))
        self.pushButton_7.setText(_translate("MainWindow", "读取配置"))
        self.pushButton_8.setText(_translate("MainWindow", "保存配置"))
        self.pushButton_9.setText(_translate("MainWindow", "确定"))
        self.groupBatConfig.setTitle(_translate("MainWindow", "批量配置文件设置"))
        self.pushButton_12.setText(_translate("MainWindow", "导出列表"))
        self.pushButton_13.setText(_translate("MainWindow", "清空列表"))
        self.pushButton_14.setText(_translate("MainWindow", "确定"))
        self.pushButton_15.setText(_translate("MainWindow", "删除文件"))
        self.label_16.setText(_translate("MainWindow", "配置文件列表"))
        self.pushButton_16.setText(_translate("MainWindow", "添加文件"))
        self.pushButton_17.setText(_translate("MainWindow", "读取列表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabconfig), _translate("MainWindow", "Config"))
        self.groupBox_4.setTitle(_translate("MainWindow", "网络设定"))
        self.label_19.setText(_translate("MainWindow", "网络数据文件列表"))
        self.pushButton_19.setText(_translate("MainWindow", "添加"))
        self.pushButton_20.setText(_translate("MainWindow", "删除"))
        self.pushButton_22.setText(_translate("MainWindow", "清空列表"))
        self.pushButton_23.setText(_translate("MainWindow", "确定"))
        self.groupBox_5.setTitle(_translate("MainWindow", "配置文件设定"))
        self.pushButton_24.setText(_translate("MainWindow", "确定"))
        self.pushButton_25.setText(_translate("MainWindow", "添加"))
        self.pushButton_26.setText(_translate("MainWindow", "清空列表"))
        self.label_20.setText(_translate("MainWindow", "配置文件列表"))
        self.pushButton_27.setText(_translate("MainWindow", "删除"))
        self.groupBox_6.setTitle(_translate("MainWindow", "用例设定"))
        self.pushButton_30.setText(_translate("MainWindow", "删除"))
        self.label_21.setText(_translate("MainWindow", "网络数据文件列表"))
        self.pushButton_32.setText(_translate("MainWindow", "添加"))
        self.pushButton_33.setText(_translate("MainWindow", "添加"))
        self.label_22.setText(_translate("MainWindow", "配置文件列表"))
        self.pushButton_36.setText(_translate("MainWindow", "删除"))
        self.pushButton_37.setText(_translate("MainWindow", "读取用例"))
        self.pushButton_38.setText(_translate("MainWindow", "保存用例"))
        self.pushButton_39.setText(_translate("MainWindow", "清空设置"))
        self.pushButton_40.setText(_translate("MainWindow", "确定"))
        self.label_25.setText(_translate("MainWindow", "EPoch"))
        self.label_23.setText(_translate("MainWindow", "选择网络"))
        self.label_24.setText(_translate("MainWindow", "Batch Size"))
        self.pushButton_29.setText(_translate("MainWindow", "打开文件"))
        self.label_27.setText(_translate("MainWindow", "生成路径"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabcase), _translate("MainWindow", "TestCase"))
        self.groupBox_8.setTitle(_translate("MainWindow", "配置文件信息"))
        self.groupBox_7.setTitle(_translate("MainWindow", "网络信息"))
        self.groupBox_9.setTitle(_translate("MainWindow", "硬件模拟设置"))
        self.groupBox_12.setTitle(_translate("MainWindow", "结果分析选项"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_2.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_3.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_4.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_5.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_6.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_7.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_8.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_9.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_10.setText(_translate("MainWindow", "CheckBox"))
        self.pushButton_35.setText(_translate("MainWindow", "PushButton"))
        self.groupBox_13.setTitle(_translate("MainWindow", "结果显示设置"))
        self.checkBox_11.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_12.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_13.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_14.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_15.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_16.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_17.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_18.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_19.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_20.setText(_translate("MainWindow", "CheckBox"))
        self.pushButton_41.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "Hardware Simulation"))
        self.groupBox_10.setTitle(_translate("MainWindow", "结果显示"))
        self.pushButton_31.setText(_translate("MainWindow", "保存结果"))
        self.groupBox_11.setTitle(_translate("MainWindow", "分析显示"))
        self.pushButton_34.setText(_translate("MainWindow", "保存分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabresult), _translate("MainWindow", "Result"))

